version: '3.8' # Especifica la versión de Compose

services:
  postgres_db:
    image: postgres:latest # Imagen de PostgreSQL
    container_name: postgres_service
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smartpokeprod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  recipe_scraper:
    build: ./recipe_webservice # Ruta a tu servicio de scraping de recetas
    image: recipe_scraper_image # Imagen de tu aplicación de scraping
    container_name: recipe_scraper_service
    depends_on:
      - postgres_db # Este servicio depende de postgres_db
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres_db:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: smartpokeprod

  smartpoke_core:
    build: ./smartpoke_core/smartpoke.api # Ruta a tu servicio de smartpoke core
    image: smartpoke_core_image # Imagen de tu aplicación smartpoke core
    container_name: smartpoke_core_service
    depends_on:
      - postgres_db # Este servicio depende de postgres_db
      - recipe_scraper
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:postgresql://postgres_db:5432/postgres
      DB_USER: postgres
      DB_PASSWORD: smartpokeprod

volumes:
  pgdata: # Volumen para persistencia de datos de PostgreSQL
